sudo: false
language: java
dist: trusty

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - oraclejdk8

script:
  - mvn test jacoco:report

after_success:
  - mvn coveralls:report

notifications:
  email: false

# whitelist
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
